apiVersion: inlined.example.org/v1alpha1
kind: Step
metadata:
  name: inlined-example
spec:
  composite: |
    class Composite(BaseComposite):
      def compose(self):
        self.logger.info('Debug World!')
        self.status.composite = 'Hello, World!'
